"""empty message

Revision ID: 92ceda8a8716
Revises: 3d6808641107
Create Date: 2024-02-14 16:56:01.218446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ceda8a8716'
down_revision = '3d6808641107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.drop_column('refresh_tok')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_tok', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)

    # ### end Alembic commands ###
